alertmanager:
  resources: 
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 10m
      memory: 32Mi

nodeExporter:
  resources: 
    requests:
      cpu: 10m #default 100m
      memory: 30Mi
    limits:
      cpu: 10m #default 200m
      memory: 50Mi

server:
  strategy:
    type: Recreate
  resources: 
    requests:
      cpu: 50m #default 500m
      memory: 840Mi
    limits:
      cpu: 50m #default 500m
      memory: 1000Mi

pushgateway:
  resources: 
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      cpu: 5m
      memory: 32Mi

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'microservice-user'
        scrape_interval: 5s
        static_configs:
          - targets: ['http://microservice-user:8888']