alertmanager:
  resources: 
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 10m
      memory: 32Mi

nodeExporter:
  resources: 
    requests:
      cpu: 10m #default 100m
      memory: 30Mi
    limits:
      cpu: 10m #default 200m
      memory: 50Mi

server:
  strategy:
    type: Recreate
  resources: 
    requests:
      cpu: 50m #default 500m
      memory: 840Mi
    limits:
      cpu: 50m #default 500m
      memory: 1000Mi

pushgateway:
  resources: 
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      cpu: 5m
      memory: 32Mi
